name: moshaf
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.5
  image: ^4.0.15
  shared_preferences: ^2.3.4
  smooth_page_indicator: ^1.2.1
  share_plus: ^10.1.4
  pdf: ^3.11.3
  #cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/splash.png
    - assets/tessdata_config.json
    - assets/tessdata/ara.traineddata
 
  fonts:
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lateef-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lateef-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lateef-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lateef-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lateef-SemiBold.ttf
          weight: 600
    - family: almushaf
      fonts:
        - asset: assets/fonts/almushaf.ttf
          weight: 700
 
