// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4CDj8KiQiLqSuQmaZqYT5qKfNwIzpdE0',
    appId: '1:536049852305:web:6b8e811907b207977cc430',
    messagingSenderId: '536049852305',
    projectId: 'project-2d6bb',
    authDomain: 'project-2d6bb.firebaseapp.com',
    databaseURL: 'https://project-2d6bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project-2d6bb.firebasestorage.app',
    measurementId: 'G-YSB93S5DKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWMaZrI-rjQzTBsTKuHSy9_q0xePGVLd4',
    appId: '1:536049852305:android:cfceb817c07e40097cc430',
    messagingSenderId: '536049852305',
    projectId: 'project-2d6bb',
    databaseURL: 'https://project-2d6bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project-2d6bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDlyODwNsCb16IQQUXHVNsHs70UZGSPcw',
    appId: '1:536049852305:ios:8c2df0757dbca1d17cc430',
    messagingSenderId: '536049852305',
    projectId: 'project-2d6bb',
    databaseURL: 'https://project-2d6bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project-2d6bb.firebasestorage.app',
    iosBundleId: 'com.example.moshaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDlyODwNsCb16IQQUXHVNsHs70UZGSPcw',
    appId: '1:536049852305:ios:8c2df0757dbca1d17cc430',
    messagingSenderId: '536049852305',
    projectId: 'project-2d6bb',
    databaseURL: 'https://project-2d6bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project-2d6bb.firebasestorage.app',
    iosBundleId: 'com.example.moshaf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtcdQE5d3D9sbdgKUapIcJtmPDmEy6MFA',
    appId: '1:536049852305:web:e7ae022ed0e6dd747cc430',
    messagingSenderId: '536049852305',
    projectId: 'project-2d6bb',
    authDomain: 'project-2d6bb.firebaseapp.com',
    databaseURL: 'https://project-2d6bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project-2d6bb.firebasestorage.app',
    measurementId: 'G-B5K1X1RZNB',
  );
}
